name: ci
description: Unit testing and other CI steps
inputs:
  PROVENA_ADMIN_OFFLINE_TOKEN:
    description: "Provena Offline Token"
    required: true
  DOMAIN:
    description: "Domain"
    required: true
  REALM_NAME:
    description: "Realm Name"
    required: true
  CLIENT_ID:
    description: "Client ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      shell: bash
      run: poetry install

    - name: Mypy type check
      shell: bash
      run: poetry run mypy .

    - name: Test with pytest
      shell: bash
      env:
        PROVENA_ADMIN_OFFLINE_TOKEN: ${{inputs.PROVENA_ADMIN_OFFLINE_TOKEN}}
        DOMAIN: ${{inputs.DOMAIN}}
        REALM_NAME: ${{inputs.REALM_NAME}}
        CLIENT_ID: ${{inputs.CLIENT_ID}}
      run: poetry run pytest tests/ --cov=provenaclient --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml

    - name: Build documentation
      shell: bash
      run: poetry run make html --directory docs/