name: on_pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: CI
        uses: ./.github/actions/ci
        with:
          PROVENA_OFFLINE_TOKEN: ${{secrets.prod.PROVENA_OFFLINE_TOKEN}}
          DOMAIN: ${{secrets.prod.DOMAIN}}
          REALM_NAME: ${{secrets.prod.REALM_NAME}}
          CLIENT_ID: ${{secrets.prod.CLIENT_ID}}
