name: on_pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: CI
        uses: ./.github/actions/ci
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
