name: on_push_main

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: CI
        uses: ./.github/actions/ci
        with:
          PROVENA_ADMIN_OFFLINE_TOKEN: ${{secrets.PROVENA_ADMIN_OFFLINE_TOKEN}}
          DOMAIN: ${{secrets.DOMAIN}}
          REALM_NAME: ${{secrets.REALM_NAME}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}

  cd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    needs: ci
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: CD
        uses: ./.github/actions/cd
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}