name: test_ci_only_on_branch

on:
  push:
    branches:
      - modular-actions-setup

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: CI
        uses: ./.github/actions/ci
